data_dir: /data/s4585711/vit/
image_size: [240,256]
cropped_image_size: [192,160]
cropped_pos: [20,36]
batch_size: 128
transformer_layers: 6
patch_size: 32
hidden_size: 256
num_heads: 8
mlp_dim: 512
num_classes: 2
dropout: 0.1
emb_dropout: 0.2
epochs: 120
learning_rate: 2.e-3